image: gradle:6.9.3-jdk11-alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script:
    - echo "Building $MODULE"
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - echo "Testing $MODULE"
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
  artifacts:
    paths:
      - build/jacocoHtml
after_script:
  - echo "End CI"